name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - name: Generate JWT secret for build
      run: openssl rand -out backend/src/secret.key 32
    - name: Install Trunk
      run: cargo install --locked trunk
    - name: Install frontend CSS toolchain
      run: npm install
      working-directory: frontend
    - name: Build frontend with Trunk
      run: trunk build --release
      working-directory: frontend
    - name: Build backend
      run: cargo build --verbose -p jheffmedia-site-backend --features forward-frontend
    - name: Run backend tests
      run: cargo test --verbose -p jheffmedia-site-backend
    - name: Run frontend tests
      run: cargo test --verbose -p jheffmedia-site-frontend
